permit:
  - BSD.*
  - CC0.*
  - MIT.*
  - Apache.*
  - MPL.*
  - ISC
  - WTFPL
  - GPL-3.0

ignore-packages:
  # crypto/internal/boring is released under the openSSL license as a part of the Golang Standard Library
  - crypto/internal/boring